apiVersion: dapr.io/v1
kind: Component
metadata:
  name: keyvault
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: "../.components/secrets.json"
  - name: nestedSeparator
    value: ":"
  - name: multiValued
    value: "false"